-- liquibase formatted sql

-- changeset ahmet:1713813011239-1
CREATE SEQUENCE  IF NOT EXISTS "revinfo_seq" AS bigint START WITH 1 INCREMENT BY 50 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;

-- changeset ahmet:1713813011239-2
CREATE TABLE "privilege" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "is_active" BOOLEAN, "create_date" TIMESTAMP WITHOUT TIME ZONE, "create_user" BIGINT, "unique_id" VARCHAR(255), "update_date" TIMESTAMP WITHOUT TIME ZONE, "update_user" BIGINT, "name" VARCHAR(255), "parent_id" BIGINT, "title" VARCHAR(255), CONSTRAINT "privilege_pkey" PRIMARY KEY ("id"));

-- changeset ahmet:1713813011239-3
CREATE TABLE "privilege_audit" ("id" BIGINT NOT NULL, "rev" INTEGER NOT NULL, "revtype" SMALLINT, "is_active" BOOLEAN, "create_date" TIMESTAMP WITHOUT TIME ZONE, "create_user" BIGINT, "unique_id" VARCHAR(255), "update_date" TIMESTAMP WITHOUT TIME ZONE, "update_user" BIGINT, "name" VARCHAR(255), "parent_id" BIGINT NOT NULL, "title" VARCHAR(255));

-- changeset ahmet:1713813011239-4
CREATE TABLE "revinfo" ("rev" INTEGER NOT NULL, "revtstmp" BIGINT, CONSTRAINT "revinfo_pkey" PRIMARY KEY ("rev"));

-- changeset ahmet:1713813011239-5
CREATE TABLE "role" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "is_active" BOOLEAN, "create_date" TIMESTAMP WITHOUT TIME ZONE, "create_user" BIGINT, "unique_id" VARCHAR(255), "update_date" TIMESTAMP WITHOUT TIME ZONE, "update_user" BIGINT, "name" VARCHAR(255), CONSTRAINT "role_pkey" PRIMARY KEY ("id"));

-- changeset ahmet:1713813011239-6
CREATE TABLE "role_audit" ("id" BIGINT NOT NULL, "rev" INTEGER NOT NULL, "revtype" SMALLINT, "is_active" BOOLEAN, "create_date" TIMESTAMP WITHOUT TIME ZONE, "create_user" BIGINT, "unique_id" VARCHAR(255), "update_date" TIMESTAMP WITHOUT TIME ZONE, "update_user" BIGINT, "name" VARCHAR(255));

-- changeset ahmet:1713813011239-7
CREATE TABLE "role_privilege" ("fk_role_id" BIGINT NOT NULL, "fk_privilege_id" BIGINT NOT NULL);

-- changeset ahmet:1713813011239-8
CREATE TABLE "role_privilege_audit" ("rev" INTEGER NOT NULL, "fk_role_id" BIGINT NOT NULL, "fk_privilege_id" BIGINT NOT NULL, "revtype" SMALLINT, CONSTRAINT "role_privilege_audit_pkey" PRIMARY KEY ("rev", "fk_role_id", "fk_privilege_id"));

-- changeset ahmet:1713813011239-9
CREATE TABLE "user_role" ("fk_user_id" BIGINT NOT NULL, "fk_role_id" BIGINT NOT NULL);

-- changeset ahmet:1713813011239-10
CREATE TABLE "user_role_audit" ("rev" INTEGER NOT NULL, "fk_user_id" BIGINT NOT NULL, "fk_role_id" BIGINT NOT NULL, "revtype" SMALLINT, CONSTRAINT "user_role_audit_pkey" PRIMARY KEY ("rev", "fk_user_id", "fk_role_id"));

-- changeset ahmet:1713813011239-11
CREATE TABLE "users" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "is_active" BOOLEAN, "create_date" TIMESTAMP WITHOUT TIME ZONE, "create_user" BIGINT, "unique_id" VARCHAR(255), "update_date" TIMESTAMP WITHOUT TIME ZONE, "update_user" BIGINT, "address" VARCHAR(255), "email" VARCHAR(255), "name" VARCHAR(255), "password" VARCHAR(255), "surname" VARCHAR(255), CONSTRAINT "users_pkey" PRIMARY KEY ("id"));

-- changeset ahmet:1713813011239-12
CREATE TABLE "users_audit" ("id" BIGINT NOT NULL, "rev" INTEGER NOT NULL, "revtype" SMALLINT, "is_active" BOOLEAN, "create_date" TIMESTAMP WITHOUT TIME ZONE, "create_user" BIGINT, "unique_id" VARCHAR(255), "update_date" TIMESTAMP WITHOUT TIME ZONE, "update_user" BIGINT, "address" VARCHAR(255), "email" VARCHAR(255), "name" VARCHAR(255), "password" VARCHAR(255), "surname" VARCHAR(255));

-- changeset ahmet:1713813011239-13
ALTER TABLE "privilege_audit" ADD CONSTRAINT "privilege_audit_pkey" PRIMARY KEY ("parent_id", "rev", "id");

-- changeset ahmet:1713813011239-14
ALTER TABLE "role_audit" ADD CONSTRAINT "role_audit_pkey" PRIMARY KEY ("rev", "id");

-- changeset ahmet:1713813011239-15
ALTER TABLE "users_audit" ADD CONSTRAINT "users_audit_pkey" PRIMARY KEY ("rev", "id");

-- changeset ahmet:1713813011239-16
ALTER TABLE "role_privilege_audit" ADD CONSTRAINT "fk7ihn6c9id6xemjay8n638tg9l" FOREIGN KEY ("rev") REFERENCES "revinfo" ("rev") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset ahmet:1713813011239-17
ALTER TABLE "privilege" ADD CONSTRAINT "fkahyelx161ukoxm5ont8yfsbgu" FOREIGN KEY ("parent_id") REFERENCES "privilege" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset ahmet:1713813011239-18
ALTER TABLE "users_audit" ADD CONSTRAINT "fkc949ty2p8metf4krhi4qtk25k" FOREIGN KEY ("rev") REFERENCES "revinfo" ("rev") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset ahmet:1713813011239-19
ALTER TABLE "user_role_audit" ADD CONSTRAINT "fkdjl9ndf4cevrnchltxctk79lq" FOREIGN KEY ("rev") REFERENCES "revinfo" ("rev") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset ahmet:1713813011239-20
ALTER TABLE "user_role" ADD CONSTRAINT "fkfh5cd5dto0lin09k3niq509ur" FOREIGN KEY ("fk_user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset ahmet:1713813011239-21
ALTER TABLE "role_privilege" ADD CONSTRAINT "fkfmvrk20793tbiu9f25yc9bglq" FOREIGN KEY ("fk_role_id") REFERENCES "role" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset ahmet:1713813011239-22
ALTER TABLE "role_audit" ADD CONSTRAINT "fkg268le7safjx70okmb2d6n03b" FOREIGN KEY ("rev") REFERENCES "revinfo" ("rev") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset ahmet:1713813011239-23
ALTER TABLE "privilege" ADD CONSTRAINT "fkhyv4umb04x9csyp2fo833fppb" FOREIGN KEY ("id") REFERENCES "privilege" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset ahmet:1713813011239-24
ALTER TABLE "privilege_audit" ADD CONSTRAINT "fkjb5w0607ody5hw1nmb5m3i83e" FOREIGN KEY ("rev") REFERENCES "revinfo" ("rev") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset ahmet:1713813011239-25
ALTER TABLE "role_privilege" ADD CONSTRAINT "fklevhj4fda5j3q4fghgggfk5pd" FOREIGN KEY ("fk_privilege_id") REFERENCES "privilege" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset ahmet:1713813011239-26
ALTER TABLE "user_role" ADD CONSTRAINT "fkmcxqgkmrdj4o9ghi1o5o31cep" FOREIGN KEY ("fk_role_id") REFERENCES "role" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

