-- liquibase formatted sql

-- changeset ahmet:1713874271880-1
CREATE TABLE "privilege" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "is_active" BOOLEAN DEFAULT TRUE NOT NULL, "unique_id" VARCHAR(36), "create_date" TIMESTAMP WITHOUT TIME ZONE, "create_user" BIGINT, "update_date" TIMESTAMP WITHOUT TIME ZONE, "update_user" BIGINT, "name" VARCHAR(50) NOT NULL, "title" VARCHAR(150) NOT NULL, "parent_id" BIGINT, CONSTRAINT "privilege_pk" PRIMARY KEY ("id"));

-- changeset ahmet:1713874271880-2
CREATE TABLE "role" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 4) NOT NULL, "is_active" BOOLEAN DEFAULT TRUE NOT NULL, "unique_id" VARCHAR(36), "create_date" TIMESTAMP WITHOUT TIME ZONE, "create_user" BIGINT, "update_date" TIMESTAMP WITHOUT TIME ZONE, "update_user" BIGINT, "name" VARCHAR(100), CONSTRAINT "role_pk" PRIMARY KEY ("id"));

-- changeset ahmet:1713874271880-3
CREATE TABLE "users" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 3) NOT NULL, "is_active" BOOLEAN DEFAULT TRUE NOT NULL, "unique_id" VARCHAR(36), "create_date" TIMESTAMP WITHOUT TIME ZONE, "create_user" BIGINT, "update_date" TIMESTAMP WITHOUT TIME ZONE, "update_user" BIGINT, "email" VARCHAR(150) NOT NULL, "password" VARCHAR(150) NOT NULL, "name" VARCHAR(100), "surname" VARCHAR(100), "address" VARCHAR(500), CONSTRAINT "users_pk" PRIMARY KEY ("id"));

-- changeset ahmet:1713874271880-4
CREATE TABLE "test" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 6) NOT NULL, "is_active" BOOLEAN DEFAULT TRUE NOT NULL, "unique_id" VARCHAR(36), "create_date" TIMESTAMP WITHOUT TIME ZONE, "create_user" BIGINT, "update_date" TIMESTAMP WITHOUT TIME ZONE, "update_user" BIGINT, "name" VARCHAR(50) NOT NULL, CONSTRAINT "test_pk" PRIMARY KEY ("id"));

-- changeset ahmet:1713874271880-5
CREATE TABLE "role_privilege" ("fk_role_id" BIGINT NOT NULL, "fk_privilege_id" BIGINT NOT NULL);

-- changeset ahmet:1713874271880-6
CREATE TABLE "user_role" ("fk_user_id" BIGINT NOT NULL, "fk_role_id" BIGINT NOT NULL);

-- changeset ahmet:1713874271880-7
CREATE INDEX "role_name_is_active_index" ON "role"("name", "is_active");

-- changeset ahmet:1713874271880-8
ALTER TABLE "role_privilege" ADD CONSTRAINT "role_privilege_uniq" UNIQUE ("fk_role_id", "fk_privilege_id");

-- changeset ahmet:1713874271880-9
ALTER TABLE "user_role" ADD CONSTRAINT "user_role_uniq" UNIQUE ("fk_user_id", "fk_role_id");

-- changeset ahmet:1713874271880-10
CREATE SEQUENCE  IF NOT EXISTS "revinfo_seq" AS bigint START WITH 1 INCREMENT BY 50 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;

-- changeset ahmet:1713874271880-11
CREATE TABLE "privilege_audit" ("id" BIGINT NOT NULL, "rev" INTEGER NOT NULL, "revtype" SMALLINT, "is_active" BOOLEAN, "create_date" TIMESTAMP WITHOUT TIME ZONE, "create_user" BIGINT, "unique_id" VARCHAR(255), "update_date" TIMESTAMP WITHOUT TIME ZONE, "update_user" BIGINT, "name" VARCHAR(255), "parent_id" BIGINT NOT NULL, "title" VARCHAR(255));

-- changeset ahmet:1713874271880-12
CREATE TABLE "revinfo" ("rev" INTEGER NOT NULL, "revtstmp" BIGINT, CONSTRAINT "revinfo_pkey" PRIMARY KEY ("rev"));

-- changeset ahmet:1713874271880-13
CREATE TABLE "role_audit" ("id" BIGINT NOT NULL, "rev" INTEGER NOT NULL, "revtype" SMALLINT, "is_active" BOOLEAN, "create_date" TIMESTAMP WITHOUT TIME ZONE, "create_user" BIGINT, "unique_id" VARCHAR(255), "update_date" TIMESTAMP WITHOUT TIME ZONE, "update_user" BIGINT, "name" VARCHAR(255));

-- changeset ahmet:1713874271880-14
CREATE TABLE "role_privilege_audit" ("rev" INTEGER NOT NULL, "fk_role_id" BIGINT NOT NULL, "fk_privilege_id" BIGINT NOT NULL, "revtype" SMALLINT, CONSTRAINT "role_privilege_audit_pkey" PRIMARY KEY ("rev", "fk_role_id", "fk_privilege_id"));

-- changeset ahmet:1713874271880-15
CREATE TABLE "test_audit" ("id" BIGINT NOT NULL, "rev" INTEGER NOT NULL, "revtype" SMALLINT, "is_active" BOOLEAN, "create_date" TIMESTAMP WITHOUT TIME ZONE, "create_user" BIGINT, "unique_id" VARCHAR(255), "update_date" TIMESTAMP WITHOUT TIME ZONE, "update_user" BIGINT, "name" VARCHAR(255));

-- changeset ahmet:1713874271880-16
CREATE TABLE "user_role_audit" ("rev" INTEGER NOT NULL, "fk_user_id" BIGINT NOT NULL, "fk_role_id" BIGINT NOT NULL, "revtype" SMALLINT, CONSTRAINT "user_role_audit_pkey" PRIMARY KEY ("rev", "fk_user_id", "fk_role_id"));

-- changeset ahmet:1713874271880-17
CREATE TABLE "users_audit" ("id" BIGINT NOT NULL, "rev" INTEGER NOT NULL, "revtype" SMALLINT, "is_active" BOOLEAN, "create_date" TIMESTAMP WITHOUT TIME ZONE, "create_user" BIGINT, "unique_id" VARCHAR(255), "update_date" TIMESTAMP WITHOUT TIME ZONE, "update_user" BIGINT, "address" VARCHAR(255), "email" VARCHAR(255), "name" VARCHAR(255), "password" VARCHAR(255), "surname" VARCHAR(255));

-- changeset ahmet:1713874271880-18
ALTER TABLE "privilege_audit" ADD CONSTRAINT "privilege_audit_pkey" PRIMARY KEY ("parent_id", "rev", "id");

-- changeset ahmet:1713874271880-19
ALTER TABLE "role_audit" ADD CONSTRAINT "role_audit_pkey" PRIMARY KEY ("rev", "id");

-- changeset ahmet:1713874271880-20
ALTER TABLE "test_audit" ADD CONSTRAINT "test_audit_pkey" PRIMARY KEY ("rev", "id");

-- changeset ahmet:1713874271880-21
ALTER TABLE "users_audit" ADD CONSTRAINT "users_audit_pkey" PRIMARY KEY ("rev", "id");

-- changeset ahmet:1713874271880-22
ALTER TABLE "test_audit" ADD CONSTRAINT "fk4vawkjsl6jslrlg61lp67y32q" FOREIGN KEY ("rev") REFERENCES "revinfo" ("rev") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset ahmet:1713874271880-23
ALTER TABLE "role_privilege_audit" ADD CONSTRAINT "fk7ihn6c9id6xemjay8n638tg9l" FOREIGN KEY ("rev") REFERENCES "revinfo" ("rev") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset ahmet:1713874271880-24
ALTER TABLE "privilege" ADD CONSTRAINT "fkahyelx161ukoxm5ont8yfsbgu" FOREIGN KEY ("parent_id") REFERENCES "privilege" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset ahmet:1713874271880-25
ALTER TABLE "users_audit" ADD CONSTRAINT "fkc949ty2p8metf4krhi4qtk25k" FOREIGN KEY ("rev") REFERENCES "revinfo" ("rev") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset ahmet:1713874271880-26
ALTER TABLE "user_role_audit" ADD CONSTRAINT "fkdjl9ndf4cevrnchltxctk79lq" FOREIGN KEY ("rev") REFERENCES "revinfo" ("rev") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset ahmet:1713874271880-27
ALTER TABLE "user_role" ADD CONSTRAINT "fkfh5cd5dto0lin09k3niq509ur" FOREIGN KEY ("fk_user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset ahmet:1713874271880-28
ALTER TABLE "role_privilege" ADD CONSTRAINT "fkfmvrk20793tbiu9f25yc9bglq" FOREIGN KEY ("fk_role_id") REFERENCES "role" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset ahmet:1713874271880-29
ALTER TABLE "role_audit" ADD CONSTRAINT "fkg268le7safjx70okmb2d6n03b" FOREIGN KEY ("rev") REFERENCES "revinfo" ("rev") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset ahmet:1713874271880-30
ALTER TABLE "privilege" ADD CONSTRAINT "fkhyv4umb04x9csyp2fo833fppb" FOREIGN KEY ("id") REFERENCES "privilege" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset ahmet:1713874271880-31
ALTER TABLE "privilege_audit" ADD CONSTRAINT "fkjb5w0607ody5hw1nmb5m3i83e" FOREIGN KEY ("rev") REFERENCES "revinfo" ("rev") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset ahmet:1713874271880-32
ALTER TABLE "role_privilege" ADD CONSTRAINT "fklevhj4fda5j3q4fghgggfk5pd" FOREIGN KEY ("fk_privilege_id") REFERENCES "privilege" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset ahmet:1713874271880-33
ALTER TABLE "user_role" ADD CONSTRAINT "fkmcxqgkmrdj4o9ghi1o5o31cep" FOREIGN KEY ("fk_role_id") REFERENCES "role" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

